version: '3.1'

services: 

    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: foo


    app:
        build: .
        restart: always
        links: 
            - db
        depends_on: 
            - db
        ports: 
            - 80:8000
